spring.application.name=SubscriptionService
spring.datasource.url=jdbc:postgresql://localhost:5432/subscription_service
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
jwt.secretkey=${JWT_SECRET}
stripe.api.key=${STRIPE_API_KEY}